<a href="https://colab.research.google.com/github/UmeshKumarNo1/Data-Science/blob/main/dsnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

simple programs

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as npnp

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0])

[1 2 3]


In [ ]:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np
#indexing and slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
#sorting
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#concadenate
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#creating arrays with zeros and ones
import numpy as np
arr2 = np.zeros((3, 3))
arr3 = np.ones((2, 2))
print(arr2)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [ ]:
#mathematical operation
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
mat_product = np.dot(mat1, mat2)
print(mat_product)

[[19 22]
 [43 50]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(0, 10, 2)
arr3 = np.linspace(0, 1, 5)
arr4 = np.random.rand(3, 3)
print("arr1:", arr1)
print("arr2:", arr2)
print("arr3:", arr3)
print("arr4:", arr4)

arr1: [1 2 3 4 5]
arr2: [0 2 4 6 8]
arr3: [0.   0.25 0.5  0.75 1.  ]
arr4: [[0.43999363 0.90568837 0.89065736]
 [0.07301946 0.32671173 0.52457826]
 [0.81116828 0.55765506 0.52114372]]


In [ ]:
#NUMPY FUNCTIONS AND OPERATIONS

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
x=np.zeros((3,4))
print(x)
y=np.ones((2,3,4),dtype=np.int16)
print(y)
d=np.arange(10,25,5)
print(d)
w=np.linspace(0,2,9)
print(w)
e=np.full((2,2),7)
print(e)
f=np.eye(2)
print(f)
a1=np.random.random((2,2))
print(a1)
a2=np.empty((3,2))
print(a2)
x1=np.save('my_array',a)
print(x1)
x2=np.savez('array.npz',a,b)
print(x2)
x3=np.load('my_array.npy')
print(x3)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.26678344 0.64518077]
 [0.7079414  0.12094809]]
[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]
None
None
[1 2 3]


In [ ]:
import numpy as np
#creating arrays
arr1 = np.array([1, 2, 3])  # Create an array
print(arr1)
arr2 = np.zeros((2, 3))
print(arr2)
arr3 = np.ones((3, 2))  # Create a 3x2 array of ones
print(arr3)
arr4 = np.arange(0, 10, 2)  # Create an array with values from 0 to 10 with step 2
print(arr4)
arr5 = np.linspace(0, 1, 5)  # Create an array with 5 evenly spaced values between 0 and 1
print(arr5)
arr6 = np.eye(3)  # Create a 3x3 identity matrix
print(arr6)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
#array operations
# Element-wise addition
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sum_array = array1 + array2

# Element-wise multiplication
product_array = array1 * array2

# Dot product of two arrays
dot_product = np.dot(array1, array2)

# Transposing a matrix
matrix = np.array([[1, 2], [3, 4]])
transposed_matrix = matrix.T


In [ ]:
#array indexing and slicing
import numpy as np

# Accessing elements
array = np.array([[1, 2, 3], [4, 5, 6]])
element = array[0, 1]  # Accessing the element in the first row and second column

# Slicing
sliced_array = array[:, 1]  # Selecting the second column


In [ ]:
#statistical operation
import numpy as np

# Mean and standard deviation
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
std_deviation = np.std(data)

# Sum of elements
sum_of_elements = np.sum(data)


In [ ]:
#reshaping arrays
import numpy as np

# Reshaping a 1D array to a 2D array
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape(2, 3)


In [ ]:
#random number generation
import numpy as np

# Generate a random 1D array
random_array = np.random.rand(5)

# Generate a random 2D array
random_matrix = np.random.rand(3, 4)


In [ ]:
#element wise function
import numpy as np

# Applying a function element-wise
array = np.array([1, 2, 3])
squared_array = np.square(array)

# Element-wise square root
sqrt_array = np.sqrt(array);

In [ ]:
#logical operation
import numpy as np

# Creating boolean arrays
array1 = np.array([True, False, True])
array2 = np.array([False, True, True])

# Element-wise logical AND
logical_and_result = np.logical_and(array1, array2)

# Element-wise logical OR
logical_or_result = np.logical_or(array1, array2)


In [ ]:
#array concadenation
import numpy as np

# Concatenating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate along rows
concatenated_rows = np.concatenate((array1, array2))

# Concatenate along columns
concatenated_columns = np.vstack((array1, array2))


In [ ]:
#linear algebra operation
import numpy as np

# Matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix1, matrix2)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix1)


In [ ]:
#array comparison
import numpy as np

# Array comparison
array1 = np.array([1, 2, 3])
array2 = np.array([1, 5, 3])

# Element-wise comparison
elementwise_comparison = array1 == array2

# Check if all elements are equal
all_equal = np.array_equal(array1, array2)


In [ ]:
#mathematical functions
import numpy as np

# Trigonometric functions
sin_values = np.sin(np.array([0, np.pi/2, np.pi]))

# Exponential and logarithmic functions
exp_values = np.exp(np.array([1, 2, 3]))
log_values = np.log(np.array([1, 2, 3]))


In [ ]:
#array operation

#element wise operation
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Addition, subtraction, multiplication, division
result_add = np.add(array1, array2)
result_subtract = np.subtract(array1, array2)
result_multiply = np.multiply(array1, array2)
result_divide = np.divide(array1, array2)

#dotproduct
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(matrix1, matrix2)



In [ ]:
import numpy as np

# Generating Random Data
np.random.seed(42)  # Setting seed for reproducibility
data = np.random.randint(0, 100, size=(3, 5))

# Displaying the Original Data
print("Original Data:")
print(data)

# Statistical Analysis
mean_value = np.mean(data)
min_value = np.min(data)
max_value = np.max(data)
sum_values = np.sum(data, axis=1)  # Sum along each row

print("\nStatistical Analysis:")
print("Mean:", mean_value)
print("Min:", min_value)
print("Max:", max_value)
print("Sum along each row:", sum_values)

# Array Manipulation
reshaped_data = np.reshape(data, (5, 3))
transposed_data = np.transpose(data)

print("\nArray Manipulation:")
print("Reshaped Data:")
print(reshaped_data)
print("\nTransposed Data:")
print(transposed_data)

# Boolean Indexing
greater_than_50 = data[data > 50]

print("\nBoolean Indexing (Values greater than 50):")
print(greater_than_50)


In [ ]:
#I/O NUMPY PROGRAMS

In [ ]:
#SAVING AND LOADING ARRAYS
import numpy as np

# Creating an array
data = np.array([[1, 2, 3], [4, 5, 6]])

# Saving the array to a text file
np.savetxt('data.txt', data


In [ ]:
#numpy programs with data types

#Creating NumPy arrays with specified data types:

import numpy as np

# Creating an array of integers
arr_int = np.array([1, 2, 3, 4], dtype=np.int32)
print("Array of integers:", arr_int)

# Creating an array of floats
arr_float = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float64)
print("Array of floats:", arr_float)

# Creating an array of complex numbers
arr_complex = np.array([1 + 2j, 3 + 4j], dtype=np.complex128)
print("Array of complex numbers:", arr_complex)



#Changing data type of an existing array:


# Creating an array of integers
arr_int = np.array([1, 2, 3, 4])
print("Original array:", arr_int)

# Changing data type to float
arr_float = arr_int.astype(np.float64)
print("Array with float data type:", arr_float)



#Performing operations with different data types:

# Creating arrays of different data types
arr_int = np.array([1, 2, 3, 4], dtype=np.int32)
arr_float = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float64)

# Adding arrays of different data types
result = arr_int + arr_float
print("Result of addition:", result)



inspecting your array

In [ ]:
#Array Shape and Dimensions:
import numpy as np

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:")
print(arr_2d)

# Get array shape
print("Shape of the array:", arr_2d.shape)

# Get number of dimensions
print("Number of dimensions:", arr_2d.ndim)

# Get number of elements in the array
print("Number of elements:", arr_2d.size)


In [ ]:
#array data type
# Get data type of array
print("Data type of the array:", arr_2d.dtype)


In [ ]:
#array statistics

# Get minimum and maximum values
print("Minimum value:", np.min(arr_2d))
print("Maximum value:", np.max(arr_2d))

# Get mean, median, and standard deviation
print("Mean:", np.mean(arr_2d))
print("Median:", np.median(arr_2d))
print("Standard Deviation:", np.std(arr_2d))


array mathematics

In [ ]:
#element wise operation
import numpy as np

# Creating two arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
result_add = arr1 + arr2
print("Element-wise addition:")
print(result_add)

# Element-wise subtraction
result_sub = arr1 - arr2
print("Element-wise subtraction:")
print(result_sub)

# Element-wise multiplication
result_mul = arr1 * arr2
print("Element-wise multiplication:")
print(result_mul)

# Element-wise division
result_div = arr1 / arr2
print("Element-wise division:")
print(result_div)


In [ ]:
#basic operations
# Sum of all elements in the array
sum_arr = np.sum(arr1)
print("Sum of all elements:", sum_arr)

# Mean of all elements in the array
mean_arr = np.mean(arr1)
print("Mean of all elements:", mean_arr)

# Element-wise square root
sqrt_arr = np.sqrt(arr1)
print("Square root of elements:")
print(sqrt_arr)


In [ ]:
#matrix operation
# Matrix multiplication (dot product)
mat_mul = np.dot(arr1, arr2.T)  # Transpose of arr2 to make the dimensions compatible
print("Matrix multiplication (dot product):")
print(mat_mul)

# Determinant of a matrix
det_arr1 = np.linalg.det(arr1)
print("Determinant of arr1:", det_arr1)

# Inverse of a matrix
inv_arr1 = np.linalg.inv(arr1)
print("Inverse of arr1:")
print(inv_arr1)



In [ ]:
#statistical operations
# Computing the mean along a specified axis
mean_axis0 = np.mean(arr1, axis=0)
print("Mean along axis 0:")
print(mean_axis0)

# Computing the standard deviation along a specified axis
std_axis1 = np.std(arr1, axis=1)
print("Standard deviation along axis 1:")
print(std_axis1)


Aggregate function

In [ ]:
#sum

# Computing the mean along a specified axis
mean_axis0 = np.mean(arr1, axis=0)
print("Mean along axis 0:")
print(mean_axis0)

# Computing the standard deviation along a specified axis
std_axis1 = np.std(arr1, axis=1)
print("Standard deviation along axis 1:")
print(std_axis1)


In [ ]:
# Mean of all elements in the array
mean_value = np.mean(arr)
print("Mean of all elements:", mean_value)

# Mean along a specific axis
mean_axis0 = np.mean(arr, axis=0)
print("Mean along axis 0:", mean_axis0)

mean_axis1 = np.mean(arr, axis=1)
print("Mean along axis 1:", mean_axis1)


In [ ]:
# Minimum and maximum values in the array
min_value = np.min(arr)
max_value = np.max(arr)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# Minimum and maximum along a specific axis
min_axis0 = np.min(arr, axis=0)
max_axis1 = np.max(arr, axis=1)
print("Minimum along axis 0:", min_axis0)
print("Maximum along axis 1:", max_axis1)


In [ ]:
# Median of all elements in the array
median_value = np.median(arr)
print("Median of all elements:", median_value)

# Median along a specific axis
median_axis0 = np.median(arr, axis=0)
print("Median along axis 0:", median_axis0)

median_axis1 = np.median(arr, axis=1)
print("Median along axis


In [ ]:
# Standard deviation of all elements in the array
std_deviation = np.std(arr)
print("Standard deviation of all elements:", std_deviation)

# Standard deviation along a specific axis
std_deviation


copying arrays

In [ ]:
#shallow copy
import numpy as np

# Creating an array
arr_original = np.array([1, 2, 3, 4, 5])

# Creating a shallow copy
arr_shallow_copy = arr_original.view()

# Modifying the copy
arr_shallow_copy[0] = 99

# Both arrays are affected
print("Original array:", arr_original)
print("Shallow copy:", arr_shallow_copy)


In [ ]:
#deep copy
import numpy as np

# Creating an array
arr_original = np.array([1, 2, 3, 4, 5])

# Creating a deep copy
arr_deep_copy = arr_original.copy()

# Modifying the copy
arr_deep_copy[0] = 99

# Only the copy is affected
print("Original array:", arr_original)
print("Deep copy:", arr_deep_copy)


sorting   arrays

In [ ]:
#sorting along axis
import numpy as np

# Creating an array
arr = np.array([[3, 2, 1], [6, 5, 4]])

# Sorting along the last axis (axis=-1)
arr_sorted = np.sort(arr, axis=-1)

print("Original array:")
print(arr)
print("\nSorted array along the last axis:")
print(arr_sorted)


In [ ]:
#sorting with indices
import numpy as np

# Creating an array
arr = np.array([3, 1, 2])

# Getting indices that would sort the array
indices = np.argsort(arr)

print("Original array:")
print(arr)
print("\nIndices for sorting:")
print(indices)


In [ ]:
#sorting in place
import numpy as np

# Creating an array
arr = np.array([3, 1, 2])

# Sorting the array in place
arr.sort()

print("Sorted array in place:")
print(arr)


In [ ]:
#sorting with structured arrays
import numpy as np

# Creating a structured array
dtype = [('name', 'S10'), ('age', int), ('height', float)]
data = [('Alice', 25, 5.6), ('Bob', 30, 5.9), ('Charlie', 22, 5.8)]
arr = np.array(data, dtype=dtype)

# Sorting the structured array based on the 'age' field
arr_sorted = np.sort(arr, order='age')

print("Original structured array:")
print(arr)
print("\nSorted structured array based on age:")
print(arr_sorted)


subsetting,slicing,indexing

In [ ]:
#indexing
import numpy as np

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
element = arr_2d[1, 2]
print("Element at index (1, 2):", element)


Element at index (1, 2): 6


In [ ]:
#slicing
# Slicing a 2D array
slice_2d = arr_2d[0:2, 1:3]
print("Sliced 2D array:")
print(slice_2d)


In [ ]:
# Boolean indexing
bool_index = arr_2d[arr_2d > 5]
print("Elements greater than 5:")
print(bool_index)


In [ ]:
# Integer array indexing
indices = np.array([0, 2])
selected_rows = arr_2d[indices, :]
print("Selected rows using integer array indexing:")
print(selected_rows)


In [ ]:
# Modifying a slice of the array
arr_2d[1:, 1:] = 0
print("Modified array:")
print(arr_2d)


In [ ]:
# Subsetting a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])
subset = arr_1d[arr_1d > 20]
print("Subset of 1D array where elements are greater than 20:")
print(subset)


Array manipulation

In [ ]:
#Reshaping:Changing the shape of an array.
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to a 2D array
arr_reshaped = arr.reshape(2, 3)
print("Original array:")
print(arr)
print("\nReshaped array:")
print(arr_reshaped)


In [ ]:
#flattening
# Flattening a 2D array
arr_flattened = arr_reshaped.flatten()
print("Flattened array:")
print(arr_flattened)


In [ ]:
#concatenation
# Creating two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenating along axis 0 (rows)
arr_concatenated = np.concatenate((arr1, arr2


In [ ]:
# Stacking arrays vertically
arr_stacked = np.vstack((arr1, arr2))
print("Vertically stacked array:")
print(arr_stacked)


In [ ]:
# Splitting an array horizontally
arr_split = np.hsplit(arr_reshaped, 3)
print("Horizontally split arrays:")
for a in arr_split:
    print(a)


In [ ]:
#transposing
# Transposing a 2D array
arr_transposed = arr_reshaped.T
print("Original array:")
print(arr_reshaped)
print("\nTransposed array:")
print(arr_transposed)
